dot -Tpng empDataInsert0.gv -o empDataInsert0.png
dot -Tpng empDataInsert1.gv -o empDataInsert1.png
dot -Tpng empDataInsert2.gv -o empDataInsert2.png
dot -Tpng empDataInsert3.gv -o empDataInsert3.png
dot -Tpng empDataInsert4.gv -o empDataInsert4.png
dot -Tpng empDataInsert5.gv -o empDataInsert5.png
dot -Tpng empDataInsert6.gv -o empDataInsert6.png
dot -Tpng empDataInsert7.gv -o empDataInsert7.png
dot -Tpng empDataInsert8.gv -o empDataInsert8.png
dot -Tpng empDataInsert9.gv -o empDataInsert9.png
dot -Tpng empDataInsert10.gv -o empDataInsert10.png
dot -Tpng empDataInsert11.gv -o empDataInsert11.png
dot -Tpng empDataInsert12.gv -o empDataInsert12.png
