dot -Tpng graph0.gv -o graph0.png
dot -Tpng graph1.gv -o graph1.png
dot -Tpng graph2.gv -o graph2.png
dot -Tpng graph3.gv -o graph3.png
dot -Tpng graph4.gv -o graph4.png
dot -Tpng graph5.gv -o graph5.png
dot -Tpng graph6.gv -o graph6.png
dot -Tpng graph7.gv -o graph7.png
dot -Tpng graph8.gv -o graph8.png
dot -Tpng graph9.gv -o graph9.png
dot -Tpng graph10.gv -o graph10.png
dot -Tpng graph11.gv -o graph11.png
dot -Tpng graph12.gv -o graph12.png
