dot -Tpng empDataDelete0.gv -o empDataDelete0.png
dot -Tpng empDataDelete1.gv -o empDataDelete1.png
dot -Tpng empDataDelete2.gv -o empDataDelete2.png
dot -Tpng empDataDelete3.gv -o empDataDelete3.png
dot -Tpng empDataDelete4.gv -o empDataDelete4.png
dot -Tpng empDataDelete5.gv -o empDataDelete5.png
dot -Tpng empDataDelete6.gv -o empDataDelete6.png
dot -Tpng empDataDelete7.gv -o empDataDelete7.png
dot -Tpng empDataDelete8.gv -o empDataDelete8.png
dot -Tpng empDataDelete9.gv -o empDataDelete9.png
dot -Tpng empDataDelete10.gv -o empDataDelete10.png
dot -Tpng empDataDelete11.gv -o empDataDelete11.png
dot -Tpng empDataDelete12.gv -o empDataDelete12.png
dot -Tpng empDataDelete13.gv -o empDataDelete13.png
dot -Tpng empDataDelete14.gv -o empDataDelete14.png
dot -Tpng empDataDelete15.gv -o empDataDelete15.png
dot -Tpng empDataDelete16.gv -o empDataDelete16.png
dot -Tpng empDataDelete17.gv -o empDataDelete17.png
dot -Tpng empDataDelete18.gv -o empDataDelete18.png
dot -Tpng empDataDelete19.gv -o empDataDelete19.png
dot -Tpng empDataDelete20.gv -o empDataDelete20.png
dot -Tpng empDataDelete21.gv -o empDataDelete21.png
dot -Tpng empDataDelete22.gv -o empDataDelete22.png
dot -Tpng empDataDelete23.gv -o empDataDelete23.png
dot -Tpng empDataDelete24.gv -o empDataDelete24.png
dot -Tpng empDataDelete25.gv -o empDataDelete25.png
dot -Tpng empDataDelete26.gv -o empDataDelete26.png
dot -Tpng empDataDelete27.gv -o empDataDelete27.png
